export const SET_ERRORS = "SET_ERRORS";
export const TOGGLE_USER_LOADING = "TOGGLE_USER_LOADING";
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CREATE_RECORD = "CREATE_RECORD";
export const UPDATE_RECORD = "UPDATE_RECORD";
export const DELETE_RECORD = "DELETE_RECORD";
export const GET_RECORD = "GET_RECORD";
export const TOGGLE_RECORD_LOADING = "RECORD_LOADING";
export const GET_RECORDS = "GET_RECORDS";
export const RESET_RECORD = "RESET_RECORD";
export const TOGGLE_RECORDS_LOADING = "RECORDS_LOADING";
